
server:
  port: 9001


spring:
  application:
    name: PRODUCT-SERVICE
  datasource:
    url: jdbc:h2:mem:product-db
    driverClassName : org.h2.Driver
    username : sa
    password: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true


  h2:
    console:
      enabled: true


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone : http://localhost:8761/eureka


okta:
  oauth2:
    issuer: https://dev-11896815.okta.com/oauth2/default
    audience: api://default


logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'


management:
  tracing:
    sampling:
      probability: 1.0