server:
  port: 8001

microservice:
  product: http://PRODUCT-SERVICE/product/
  payment: http://PAYMENTS-SERVICE/payment/

spring:
  application:
    name: ORDER-SERVICE
  datasource:
    url: jdbc:h2:mem:order-db
    driverClassName : org.h2.Driver
    username : sa
    password: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
 #   eureka-service-url-poll-interval-seconds: 1
    service-url:
      defaultZone : http://localhost:8761/eureka

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'

management:
  tracing:
    sampling:
      probability: 1.0